get_user_list: output warning to stderr
The function get_user_list returns a list of users on stdout, so
obviously it can't use stdout to also display messages. Use stderr
instead.

Note that we could also silently skip if we find a directory in /home
that is not a user. Does it happen in practice?

diff --git a/kali-config/common/includes.installer/kali-finish-install b/kali-config/common/includes.installer/kali-finish-install
--- a/kali-config/common/includes.installer/kali-finish-install
+++ b/kali-config/common/includes.installer/kali-finish-install
@@ -28,7 +28,7 @@ END
 get_user_list() {
     for user in $(cd /home && ls); do
 	if ! getent passwd "$user" >/dev/null; then
-	    echo "WARNING: user '$user' is invalid but /home/$user exists"
+	    echo "WARNING: user '$user' is invalid but /home/$user exists" >&2
 	    continue
 	fi
 	echo "$user"
