Enable zsh by default

diff --git a/simple-cdd/profiles/kali.postinst b/simple-cdd/profiles/kali.postinst
--- a/simple-cdd/profiles/kali.postinst
+++ b/simple-cdd/profiles/kali.postinst
@@ -1,17 +1,41 @@
 #!/bin/sh
 
-if grep -q '^deb ' /etc/apt/sources.list; then
-    echo "INFO: sources.list is configured, everything is fine"
-    exit 0
-fi
+configure_sources_list() {
+    if grep -q '^deb ' /etc/apt/sources.list; then
+	echo "INFO: sources.list is configured, everything is fine"
+	return
+    fi
 
-echo "INFO: sources.list is empty, setting up a default one for Kali"
+    echo "INFO: sources.list is empty, setting up a default one for Kali"
 
-cat >/etc/apt/sources.list <<END
+    cat >/etc/apt/sources.list <<END
 # See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
 deb http://http.kali.org/kali kali-rolling main contrib non-free
 
 # Additional line for source packages
 # deb-src http://http.kali.org/kali kali-rolling main contrib non-free
 END
-apt-get update
+    apt-get update
+}
+
+configure_zsh() {
+    if grep -q 'nozsh' /proc/cmdline; then
+	echo "INFO: user opted out of zsh by default"
+	return
+    fi
+    if [ ! -x /usr/bin/zsh ]; then
+	echo "INFO: /usr/bin/zsh is not available"
+	return
+    fi
+    for user in $(cd /home && ls); do
+	if ! getent passwd $user >/dev/null; then
+	    echo "WARNING: user '$user' is invalid but /home/$user exists"
+	    continue
+	fi
+	echo "INFO: changing default shell of user '$user' to zsh"
+	chsh --shell /usr/bin/zsh $user
+    done
+}
+
+configure_sources_list
+configure_zsh
